# --- Basic options --- #

# Name of website
title: 爱吃烤鱼的小伙伴

# Short description of your site
description: 生命就是等待正确的行动时机

# Your name to show in the footer
author: 亮亮

theme: jekyll-theme-architect

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "关于我"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: ""

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar-icon.jpeg"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image